### PR TITLE
Create CONTRIBUTION.md

### PR DESCRIPTION
**Pull request by Kreyren**
I like your project and i would like to help.

Can you write a CONTRIBUTION.md so that i and other contributors know how to help? (if you still plan to develop it)

### CODE REVIEW

**Comment by 0x5c** [comment]
`(if you still plan to develop it)`
Good precision

**Comment by YePpHa** [comment]
👍

**Comment by Kreyren** [comment]
@YePpHa Can you share why? I'm interested in forking it.

**Comment by salmanulfarzy** [comment]
> Can you share why?

@YePpHa explained it on another thread,

> Sorry guys. I've been kind of busy. While I had time to do coding I've either been working on some of my other projects or playing games. I'm moving very soon so after that I should be able to start working on this again.

- https://github.com/YePpHa/maia-yt/issues/118#issuecomment-442488951

**Comment by Kreyren** [comment]
Thanks for info

**Comment by YePpHa** [comment]
@Kreyren a small update. I've finally gotten to adding a contributing file. You can look

**Comment by Kreyren** [comment]
Noted, will check

**Comment by YePpHa** [comment]
@Kreyren also if you find something weird or strange with it. Please let me know.

**Pull request closed without merging**
